dxgi.customVendorId = 10de
dxgi.customDeviceId = 7687
dxgi.customDeviceDesc = "NVIDIA GeForce RTX 2080 Ti"
d3d9.customVendorId = 10de
d3d9.customDeviceId = 7687
d3d9.customDeviceDesc = "NVIDIA GeForce RTX 2080 Ti"
dxgi.hideNvidiaGpu = False
