"""Bit-faithful NumPy reference simulator of the FSR4 INT8 conv graph (passes 0-13, quality preset).

Mirrors the autogenerated HLSL exactly:
  - int32 dot-product accumulation (dot4add_i8packed)
  - fp32 dequant with the SAME multiply order as each shader call site
  - fp16 biases (stored fp16, added in fp32)
  - round() = half away from zero; pack_clamp_s8 = saturate [-128,127]; ReLU applied post-quant = clamp(q,0,127)
  - grouped tensors: channel halves [0,C/2)/[C/2,C) at two scales
  - pass13 CT2D output: fp16(acc*scale) + fp16 bias, added in fp16
Tensors are NHWC numpy arrays: {"q": int8 [H,W,C], "s": float} or {"q": int8, "s0": float, "s1": float}.
"""
import json
from pathlib import Path
import numpy as np

ART = Path(__file__).resolve().parents[1] / "artifacts"
F32 = np.float32
F16 = np.float16

def f32(x): return np.asarray(x, dtype=F32)

def round_half_away(x):
    return (np.sign(x) * np.floor(np.abs(x) + F32(0.5))).astype(np.int64)

def clamp_s8(q):  return np.clip(q, -128, 127).astype(np.int8)
def relu_s8(q):   return np.clip(q, 0, 127).astype(np.int8)

# ---------------------------------------------------------------- int8 conv cores
def conv2d_i8(x_q, w, stride=1, pad=0, groups=1):
    """x_q int8 [H,W,C]; w int8 [Cout, Cin//groups, kh, kw] (OIHW). Returns int64 [H',W',Cout]."""
    H, W, C = x_q.shape
    Cout, Cg, kh, kw = w.shape
    assert Cg * groups == C
    xp = np.zeros((H + 2*pad, W + 2*pad, C), dtype=np.int32)
    xp[pad:pad+H, pad:pad+W] = x_q
    xi = xp.astype(np.int32)
    Ho = (H + 2*pad - kh)//stride + 1
    Wo = (W + 2*pad - kw)//stride + 1
    acc = None
    for ky in range(kh):
        for kx in range(kw):
            patch = xi[ky:ky+stride*Ho:stride, kx:kx+stride*Wo:stride,:] # [Ho,Wo,C]
            wsl = w[:,:, ky, kx].astype(np.int32) # [Cout,C]
            if groups == 1:
                m = (patch.reshape(-1, C) @ wsl.T).reshape(patch.shape[0], patch.shape[1], -1)
            elif groups == Cout:  # depthwise
                m = patch * wsl[:, 0][None, None,:]
            else:                 # grouped: block matmul per group
                m = np.empty((patch.shape[0], patch.shape[1], Cout), dtype=np.int64)
                cg = C // groups
                for g in range(groups):
                    m[:,:, g*cg:(g+1)*cg] = patch[:,:, g*cg:(g+1)*cg] @ wsl[g*cg:(g+1)*cg,:].T
            acc = m if acc is None else acc + m
    return acc.astype(np.int64)

def convtranspose2x2_i8(x_q, w):
    """CT2D k=2 s=2: out[2y+j, 2x+i, o] = sum_c w[c, o, j, i]*x[y, x, c]. w int8 [Cin, Cout, 2, 2]."""
    H, W, C = x_q.shape
    Cout = w.shape[1]
    out = np.zeros((2*H, 2*W, Cout), dtype=np.int64)
    xi = x_q.astype(np.int32)
    for j in range(2):
        for i in range(2):
            m = xi.reshape(-1, C) @ w[:,:, j, i].astype(np.int32) # w[cin, cout]
            out[j::2, i::2,:] = m.reshape(H, W, Cout)
    return out

# ---------------------------------------------------------------- tensor helpers
def dq(t, half=None):
    """dequantize full tensor (grouped-aware) -> f32"""
    if "s" in t:
        return t["q"].astype(F32) * F32(t["s"])
    s0, s1 = F32(t["s0"]), F32(t["s1"])
    C = t["q"].shape[2]
    out = np.empty(t["q"].shape, F32)
    out[:,:,:C//2] = t["q"][:,:,:C//2].astype(F32) * s0
    out[:,:, C//2:] = t["q"][:,:, C//2:].astype(F32) * s1
    return out

# ---------------------------------------------------------------- blocks
def convnext(x, L, rcpr0, s_mid1, rcpr1, s_mid2, s_out, prefix, sim=None):
    """ConvNextBlock: dw3x3 pad1 -> pw C->2C (+ReLU-after-quant) -> pw 2C->C -> skip add -> requant."""
    W0, b0 = L[f"{prefix}_conv_dw_weight"], L[f"{prefix}_conv_dw_bias"]
    W1, b1 = L[f"{prefix}_pw_expand_weight"], L[f"{prefix}_pw_expand_bias"]
    W2, b2 = L[f"{prefix}_pw_contract_weight"], L[f"{prefix}_pw_contract_bias"]
    sw0, sw1, sw2 = F32(L[f"scale__{prefix}_conv_dw"]), F32(L[f"scale__{prefix}_pw_expand"]), F32(L[f"scale__{prefix}_pw_contract"])
    xs = F32(x["s"])
    acc = conv2d_i8(x["q"], W0, stride=1, pad=1, groups=1)  # "conv_dw" is a full conv here (16->16)
    inputscale = xs * sw0
    q = clamp_s8(round_half_away((acc.astype(F32) * inputscale + b0) * F32(rcpr0)))
    acc = conv2d_i8(q, W1)
    inputscale = F32(s_mid1) * sw1
    q = relu_s8(clamp_s8(round_half_away((acc.astype(F32) * inputscale + b1) * F32(rcpr1))))
    acc = conv2d_i8(q, W2)
    inputscale = sw2 * F32(s_mid2)
    result = acc.astype(F32) * inputscale + b2
    result = result + x["q"].astype(F32) * xs
    q = clamp_s8(round_half_away(result * (F32(1.0) / F32(s_out))))
    return {"q": q, "s": s_out}

def k2s2b(x, L, wkey, bkey, s_w, q0, q1):
    """FusedConv2D_k2s2b: 2x2 stride 2 no pad, fp16 bias, grouped 2-scale output."""
    W, b = L[wkey], L[bkey]
    acc = conv2d_i8(x["q"], W, stride=2, pad=0)
    N = acc.shape[2]
    xs, sws = F32(x["s"]), F32(s_w)
    v = acc.astype(F32)
    # HLSL: round((acc * weights.scale * input.scale + bias) * (1.0/qf))
    r = round_half_away((v * sws * xs + b) * (F32(1.0) / F32(q0)))
    q = np.empty(acc.shape, np.int8)
    q[:,:,:N//2] = clamp_s8(r[:,:,:N//2])
    r = round_half_away((v * sws * xs + b) * (F32(1.0) / F32(q1)))
    q[:,:, N//2:] = clamp_s8(r[:,:, N//2:])
    return {"q": q, "s0": q0, "s1": q1}

def _fnb_core(xg, L, prefix, q0, q1, act, variant, order="fnb"):
    """Shared FasterNetBlock internals. Returns (fnb_f32_result[C], concat_scale) pre-skip."""
    W0, b0 = L[f"{prefix}_spatial_weight"], L[f"{prefix}_spatial_bias"]
    W1, b1 = L[f"{prefix}_pw_expand_weight"], L[f"{prefix}_pw_expand_bias"]
    W2, b2 = L[f"{prefix}_pw_contract_weight"], L[f"{prefix}_pw_contract_bias"]
    sw0, sw1, sw2 = F32(L[f"scale__{prefix}_spatial"]), F32(L[f"scale__{prefix}_pw_expand"]), F32(L[f"scale__{prefix}_pw_contract"])
    xq = xg["q"]; C = xq.shape[2]
    groups = 2 if variant == "64" else 1           # 64: grouped partial conv (2x16); 32: single 16ch
    acc = conv2d_i8(xq[:,:,:C//2], W0, stride=1, pad=1, groups=groups)
    if variant == "32" or order == "ct2d":  # acc * (q0 * sw0)  [FNB_CT2D_ADD groups parenthesized for both variants]
        pre = acc.astype(F32) * (F32(q0) * sw0) + b0
    else:                 # acc * q0 * sw0  [FasterNetBlock <64,2>]
        pre = acc.astype(F32) * F32(q0) * sw0 + b0
    q_conv = clamp_s8(round_half_away(pre * (F32(1.0) / F32(q1))))
    # concat (uniform at q1): conv half + passthrough half (passthrough requant at same scale is identity)
    concat = np.concatenate([q_conv, xq[:,:, C//2:]], axis=2)
    acc = conv2d_i8(concat, W1)
    if order == "ct2d":   # vs * (quantScale1 * w1.scale)  [FNB_CT2D_ADD groups parenthesized]
        pre = acc.astype(F32) * (F32(q1) * sw1) + b1
    else:                 # vs * quantScale1 * w1.scale  (left-to-right, both FasterNetBlock variants)
        pre = acc.astype(F32) * F32(q1) * sw1 + b1
    q_relu = relu_s8(clamp_s8(round_half_away(pre * (F32(1.0) / F32(act)))))
    acc = conv2d_i8(q_relu, W2)
    if variant == "32" and order == "fnb":  # vs * sw2 * act  [FasterNetBlock <32,1> left-to-right]
        result = acc.astype(F32) * sw2 * F32(act) + b2
    else:                 # vs * (sw2 * act)  [precomputed weightReluScale in <64,2> and FNB_CT2D_ADD]
        result = acc.astype(F32) * (sw2 * F32(act)) + b2
    return result, xq, C

def fasternet(xg, L, prefix, q0, q1, act, o0, o1, variant):
    result, xq, C = _fnb_core(xg, L, prefix, q0, q1, act, variant)
    out = np.empty(result.shape, np.int8)
    r0 = result[:,:,:C//2] + xq[:,:,:C//2].astype(F32) * F32(q0)
    out[:,:,:C//2] = clamp_s8(round_half_away(r0 * (F32(1.0) / F32(o0))))
    r1 = result[:,:, C//2:] + xq[:,:, C//2:].astype(F32) * F32(q1)
    out[:,:, C//2:] = clamp_s8(round_half_away(r1 * (F32(1.0) / F32(o1))))
    return {"q": out, "s0": o0, "s1": o1}

def fasternet_uniform(xg, L, prefix, q0, q1, act, s_out, variant):
    result, xq, C = _fnb_core(xg, L, prefix, q0, q1, act, variant)
    result[:,:,:C//2] += xq[:,:,:C//2].astype(F32) * F32(q0)
    result[:,:, C//2:] += xq[:,:, C//2:].astype(F32) * F32(q1)
    q = clamp_s8(round_half_away(result * (F32(1.0) / F32(s_out))))
    return {"q": q, "s": s_out}

def fnb_ct2d_add(xg, L, prefix, skip, q0, q1, act, s_fnb, o0, o1, variant, wct_key, bct_key, sct_key):
    """FNB (uniform output scale) + ConvTranspose 2x2 + skip Add at 2x res; grouped output."""
    result, xq, C = _fnb_core(xg, L, prefix, q0, q1, act, variant, order="ct2d")
    result[:,:,:C//2] += xq[:,:,:C//2].astype(F32) * F32(q0)
    result[:,:, C//2:] += xq[:,:, C//2:].astype(F32) * F32(q1)
    fnb_q = clamp_s8(round_half_away(result * (F32(1.0) / F32(s_fnb))))
    Wct, bct = L[wct_key], L[bct_key]
    acc = convtranspose2x2_i8(fnb_q, Wct)
    ct_scale = F32(s_fnb) * F32(L[f"scale__{sct_key}"])
    v = acc.astype(F32) * ct_scale + bct
    sk = skip["q"].astype(F32) * F32(skip["s"])
    v = v + sk
    N = v.shape[2]
    q = np.empty(v.shape, np.int8)
    q[:,:,:N//2] = clamp_s8(round_half_away(v[:,:,:N//2] * (F32(1.0) / F32(o0))))
    q[:,:, N//2:] = clamp_s8(round_half_away(v[:,:, N//2:] * (F32(1.0) / F32(o1))))
    return {"q": q, "s0": o0, "s1": o1}

def fnb_ct2d_add_uniform(xg, L, prefix, skip, q0, q1, act, s_fnb, s_out, variant, wct_key, bct_key, sct_key):
    result, xq, C = _fnb_core(xg, L, prefix, q0, q1, act, variant, order="ct2d")
    result[:,:,:C//2] += xq[:,:,:C//2].astype(F32) * F32(q0)
    result[:,:, C//2:] += xq[:,:, C//2:].astype(F32) * F32(q1)
    fnb_q = clamp_s8(round_half_away(result * (F32(1.0) / F32(s_fnb))))
    Wct, bct = L[wct_key], L[bct_key]
    acc = convtranspose2x2_i8(fnb_q, Wct)
    ct_scale = F32(s_fnb) * F32(L[f"scale__{sct_key}"])
    v = acc.astype(F32) * ct_scale + bct + skip["q"].astype(F32) * F32(skip["s"])
    return {"q": clamp_s8(round_half_away(v * (F32(1.0) / F32(s_out)))), "s": s_out}

def pass13_cnb_ct2d(x, L, prefix, rcpr0, s_mid1, rcpr1, s_mid2, s_cnb, wct_key, bct_key, sct_key):
    """Final CNB (uniform out) + CT2D 16->8, output fp16 (8ch): fp16(acc*scale)+fp16 bias (fp16 add)."""
    cnb = convnext(x, L, rcpr0, s_mid1, rcpr1, s_mid2, s_cnb, prefix)
    Wct, bct = L[wct_key], L[bct_key]
    acc = convtranspose2x2_i8(cnb["q"], Wct)
    ct_scale = F32(s_cnb) * F32(L[f"scale__{sct_key}"])
    h = (acc.astype(F32) * ct_scale).astype(F16)
    return (h + bct.astype(F16)).astype(F16)   # [2H, 2W, 8] fp16

# ---------------------------------------------------------------- layer registry
Q = "_quant_export_handler_QuantizeLinear_output_0"

def load_layers():
    z = np.load(ART / "fsr4_quality_weights.npz")
    spec = json.loads((ART / "graph_spec.json").read_text())
    L = {}
    for k in z.files:
        L[k] = z[k]
    # weight scales from decls (embedded) and bin scale table
    decl_scale = {dn.replace("post.", ""): d["scale"] for dn, d in spec["decls"].items() if d.get("scale")}
    for name in list(L.keys()):
        if name.startswith("embedded__") or name.startswith("embedded_hwcn__") or name.startswith("_"):
            sc = decl_scale.get(name)
            if sc is not None:
                L[f"scale__{name}"] = sc
    st = spec["scale_table"]
    binmap = {"encoder3_downscale_conv_w": 28, "bottleneck_rb0_spatial_w": 31, "bottleneck_rb0_pw_expand_w": 32,
              "bottleneck_rb0_pw_contract_w": 34, "bottleneck_rb1_spatial_w": 37, "bottleneck_rb1_pw_expand_w": 38,
              "bottleneck_rb1_pw_contract_w": 40, "bottleneck_rb2_spatial_w": 43, "bottleneck_rb2_pw_expand_w": 44,
              "bottleneck_rb2_pw_contract_w": 46, "bottleneck_upscale_convT_w": 48}
    for k, i in binmap.items():
        L[f"scale__{k}"] = st[i]
    # friendly aliases -> npz keys
    def emb(mod, part): return f"embedded__{mod}_{part}{Q}"
    def bias(mod, part): return f"bias__embedded_{mod}_{part}_bias"
    def reg(mod, part, wkey=None, bkey=None):
        return dict(w=wkey or emb(mod, part), b=bkey or bias(mod, part))
    A = {}
    cnb_mods = [("encoder2_ResidualBlock_0_body", "encoder2_RB0"), ("encoder2_ResidualBlock_1_body", "encoder2_RB1"),
                ("decoder2_ResidualBlock_1_body", "decoder2_RB1"), ("decoder2_ResidualBlock_2_body", "decoder2_ResidualBlock_2")]
    for mod, short in cnb_mods:
        A[f"{short}_conv_dw_weight"] = emb(mod, "conv_dw_weight")
        A[f"{short}_conv_dw_bias"] = bias(mod, "conv_dw")
        A[f"scale__{short}_conv_dw"] = decl_scale[emb(mod, "conv_dw_weight")]
        for p in ["pw_expand", "pw_contract"]:
            A[f"{short}_{p}_weight"] = emb(mod, "conv_" + p + "_weight"); A[f"{short}_{p}_bias"] = bias(mod, "conv_" + p)
            A[f"scale__{short}_{p}"] = decl_scale[emb(mod, "conv_" + p + "_weight")]
    # FNB blocks: enc3 RB0/RB1, dec3 RB1/RB2 (embedded); bottleneck RB0/1/2 (bin); decoder2 RB2 (pass13)
    fnb_mods = {
        "encoder3_ResidualBlock_0": ("embedded__encoder3_ResidualBlock_0_body_spatial_mixing_partial_conv", "encoder3_ResidualBlock_0_body"),
        "encoder3_ResidualBlock_1": ("embedded__encoder3_ResidualBlock_1_body_spatial_mixing_partial_conv", "encoder3_ResidualBlock_1_body"),
        "bottleneck_ResidualBlock_0": ("bottleneck_rb0", "bottleneck_ResidualBlock_0_body"),
        "bottleneck_ResidualBlock_1": ("bottleneck_rb1", "bottleneck_ResidualBlock_1_body"),
        "bottleneck_ResidualBlock_2": ("bottleneck_rb2", "bottleneck_ResidualBlock_2_body"),
        "decoder3_ResidualBlock_1": ("embedded__decoder3_ResidualBlock_1_body_spatial_mixing_partial_conv", "decoder3_ResidualBlock_1_body"),
        "decoder3_ResidualBlock_2": ("embedded__decoder3_ResidualBlock_2_body_spatial_mixing_partial_conv", "decoder3_ResidualBlock_2_body"),
    }
    for mod, (spatial_key, biasmod) in fnb_mods.items():
        if spatial_key.startswith("bottleneck_rb"):
            A[f"{mod}_spatial_weight"] = spatial_key + "_spatial_w"
            A[f"scale__{mod}_spatial"] = L[f"scale__{spatial_key}_spatial_w"]
            A[f"{mod}_pw_expand_weight"] = spatial_key + "_pw_expand_w"
            A[f"scale__{mod}_pw_expand"] = L[f"scale__{spatial_key}_pw_expand_w"]
            A[f"{mod}_pw_contract_weight"] = spatial_key + "_pw_contract_w"
            A[f"scale__{mod}_pw_contract"] = L[f"scale__{spatial_key}_pw_contract_w"]
        else:
            A[f"{mod}_spatial_weight"] = spatial_key + "_weight" + Q
            A[f"scale__{mod}_spatial"] = decl_scale[spatial_key + "_weight" + Q]
            A[f"{mod}_pw_expand_weight"] = emb(biasmod, "pw_expand_weight")
            A[f"scale__{mod}_pw_expand"] = decl_scale[emb(biasmod, "pw_expand_weight")]
            A[f"{mod}_pw_contract_weight"] = emb(biasmod, "pw_contract_weight")
            A[f"scale__{mod}_pw_contract"] = decl_scale[emb(biasmod, "pw_contract_weight")]
        for p, sfx in [("spatial", "spatial_mixing_partial_conv"), ("pw_expand", "pw_expand"), ("pw_contract", "pw_contract")]:
            bk = f"bias__embedded_{biasmod}_{sfx}_bias"
            assert bk in L, bk
            A[f"{mod}_{p}_bias"] = bk
    # downscale convs
    A["enc2_ds_weight"] = emb("encoder2_DownscaleStridedConv2x2", "downscale_conv_weight")
    A["enc2_ds_bias"] = bias("encoder2_DownscaleStridedConv2x2", "downscale_conv")
    A["scale__enc2_ds"] = decl_scale[A["enc2_ds_weight"]]
    A["enc3_ds_weight"] = "encoder3_downscale_conv_w"
    A["enc3_ds_bias"] = "bias__embedded_encoder3_DownscaleStridedConv2x2_downscale_conv_bias"
    A["scale__enc3_ds"] = st[28]
    # CT2D weights (HWCN, OIHW=cin,cout,ky,kx)
    A["bottleneck_ct_weight"] = "bottleneck_upscale_convT_w"; A["scale__bottleneck_ct"] = st[48]
    A["bottleneck_ct_bias"] = "bias__embedded_bottleneck_UpscaleConvTranspose2x2_upscale_conv_bias"
    A["dec3_ct_weight"] = "embedded_hwcn__decoder3_UpscaleConvTranspose2x2_upscale_conv_weight" + Q
    A["scale__dec3_ct"] = decl_scale[A["dec3_ct_weight"]]
    A["dec3_ct_bias"] = "bias__embedded_decoder3_UpscaleConvTranspose2x2_upscale_conv_bias"
    A["dec2_ct_weight"] = "embedded_hwcn__decoder2_UpscaleConvTranspose2x2_upscale_conv_weight" + Q
    A["scale__dec2_ct"] = decl_scale[A["dec2_ct_weight"]]
    A["dec2_ct_bias"] = "bias__embedded_decoder2_UpscaleConvTranspose2x2_upscale_conv_bias"
    L.update(A)
    # resolve string aliases -> arrays (scales stay float)
    for k, v in list(A.items()):
        if isinstance(v, str) and not k.startswith("scale__") and v in L and not isinstance(L[v], str):
            L[k] = L[v]
    L["_calls"] = spec["calls"]
    return L

# pass-0 (feature conv, fp16 weights, fp32 acc). features fp16 [H, W, 8] (ch7=0), W0 [f,ky,kx,c] fp16
def pass0(features_f16, L):
    """out[h,w,f] = clamp(round(((t00+t10)+(t01+t11) + bias) / s)); t_kyx = sum_c w[f,ky,kx,c]*feat[2h+ky,2w+kx,c]
    fp16 inputs/weights, fp32 accumulation (sequential tap order; shader groups (t00+t10)+(t01+t11) — ULP-level difference only)."""
    w0 = L["pass0_weight_fkyxc"].astype(F16)  # [16,2,2,8]
    b = L["pass0_bias"].astype(F32)
    H, W, _ = features_f16.shape
    xf = features_f16.astype(F32)
    acc = np.zeros((H//2, W//2, 16), dtype=F32)
    for ky in range(2):
        for kx in range(2):
            # exact fp16*fp16 products accumulated in fp32 (matches dot2add)
            t = np.einsum("hwc,fc->hwf", xf[ky::2, kx::2,:], w0[:, ky, kx,:].astype(F32))
            acc += t  # sequential tap accumulation (t00+t10)+(t01+t11) tolerance: ULP-level
    s = F32(L["_pass0_scale"])
    q = clamp_s8(round_half_away((acc + b) * (F32(1.0) / s)))
    return {"q": q, "s": float(L["_pass0_scale"])}

# ---------------------------------------------------------------- full graph
def run_graph(x_in, L=None, trace=None):
    """x_in: {"q": int8[H,W,16], "s": s_in}. Returns (output fp16 [H*2? no: [H,W,8] @ upscale res], stats)."""
    if L is None:
        L = load_layers()
    calls = L["_calls"]
    c = {i: calls[i]["args"] for i in range(len(calls))}
    # passes 1..12 + post (index 12)
    x = x_in
    outs = {}
    # pass1/2: ConvNextBlock (args: rcpr0, s_mid1, rcpr1, s_mid2)
    x = convnext(x, L, c[0][0], c[0][1], c[0][2], c[0][3], 0.01933070458471775, "encoder2_RB0")
    outs["p1"] = x
    x = convnext(x, L, c[1][0], c[1][1], c[1][2], c[1][3], 0.02335178479552269, "encoder2_RB1")
    outs["p2"] = x
    # pass3: k2s2b enc2->enc3 (args: q0,q1)
    x = k2s2b(x, L, "enc2_ds_weight", "enc2_ds_bias", L["scale__enc2_ds"], c[2][0], c[2][1]); outs["p3"] = x
    # pass4/5: FNB<32,1> (args: q0,q1,act,o0,o1)
    x = fasternet(x, L, "encoder3_ResidualBlock_0", *c[3][:5], "32"); outs["p4"] = x
    x = fasternet_uniform(x, L, "encoder3_ResidualBlock_1", *c[4][:3], 0.019347405061125755, "32"); outs["p5"] = x
    skip3 = x
    # pass6: k2s2b enc3->bottleneck
    x = k2s2b(x, L, "enc3_ds_weight", "enc3_ds_bias", L["scale__enc3_ds"], c[5][0], c[5][1]); outs["p6"] = x
    # pass7/8: FNB<64,2>
    x = fasternet(x, L, "bottleneck_ResidualBlock_0", *c[6][:5], "64"); outs["p7"] = x
    x = fasternet(x, L, "bottleneck_ResidualBlock_1", *c[7][:5], "64"); outs["p8"] = x
    # pass9: FNB_CT2D_ADD<64,2> (args: q0,q1,act,fnbOut,o0,o1)
    x = fnb_ct2d_add(x, L, "bottleneck_ResidualBlock_2", skip3, *c[8][:6], "64",
                     "bottleneck_ct_weight", "bottleneck_ct_bias", "bottleneck_ct"); outs["p9"] = x
    # pass10: FNB<32,1>
    x = fasternet(x, L, "decoder3_ResidualBlock_1", *c[9][:5], "32"); outs["p10"] = x
    # pass11: FNB_CT2D_ADD<32,1> (args: q0,q1,act,fnbOut) -> uniform out 0.027206305414438248, skip = p2
    x = fnb_ct2d_add_uniform(x, L, "decoder3_ResidualBlock_2", outs["p2"], *c[10][:4], 0.027206305414438248, "32",
                             "dec3_ct_weight", "dec3_ct_bias", "dec3_ct"); outs["p11"] = x
    # pass12: ConvNextBlock dec2/RB1 -> 0.035173576325178146
    x = convnext(x, L, c[11][0], c[11][1], c[11][2], c[11][3], 0.035173576325178146, "decoder2_RB1"); outs["p12"] = x
    # pass13: CNB+CT2D -> fp16 8ch (args: rcpr0, mid1, rcpr1, mid2, cnbOut)
    out = pass13_cnb_ct2d(x, L, "decoder2_ResidualBlock_2", *c[12][:5],
                          "dec2_ct_weight", "dec2_ct_bias", "dec2_ct")
    outs["p13"] = out
    if trace is not None:
        trace.update(outs)
    return out

# input scale of the network (encoder1 output)
S_IN = 0.014884727075695992

def load_with_pass0_scale(L):
    z = np.load(ART / "fsr4_quality_weights.npz")
    L["_pass0_scale"] = float(z["bin_scale_table"][0])
    return L
